# Generated by Django 4.0.4 on 2022-05-16 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(choices=[('RUSSIA', 'Russia'), ('KAZAKHSTAN', 'Kazakhstan'), ('KYRGYZSTAN', 'Kyrgyzstan'), ('UZBEKISTAN', 'Uzbekistan')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='favorite_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='favorite_word',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
