# Generated by Django 4.0.4 on 2022-04-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('genre', models.CharField(choices=[('Comedy', 'COMEDY'), ('Romantic', 'ROMANTIC'), ('Horror', 'Horror'), ('Fantastic', 'FANTASTIC')], max_length=100)),
                ('year_of_issue', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('shows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookFeedBack', to='book.bookshow')),
            ],
        ),
    ]
