# Generated by Django 4.0.4 on 2022-05-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookshow_bookfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
